# Generated by Django 6.0.2 on 2026-02-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeup_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makeupclass",
            name="classroom",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="makeupclass",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="makeupclass",
            name="remedial_code",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="makeupclass",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
