# Generated by Django 6.0.2 on 2026-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeup_backend", "0002_alter_makeupclass_classroom_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makeupclass",
            name="description",
        ),
        migrations.AlterField(
            model_name="makeupclass",
            name="remedial_code",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
